require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'loyaltyDemo' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"


  #pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  target 'loyaltyDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.125.0'}) # should match the version of your Flipper client app
  
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'loyaltyDemo-tvOS' do
  # Pods for loyaltyDemo-tvOS

  target 'loyaltyDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
