export const CONTENT = 'content';

export const CONTENT_REQUEST = 'content_request';
export const CONTENT_SUCCESS = 'content_success';
export const CONTENT_FAILURE = 'content_failure';

export const CONTENT_CATEGORIES_RESET = 'CONTENT_CATEGORIES_RESET';
export const CONTENT_CATEGORIES_REQUEST = 'content_categories_request';
export const CONTENT_CATEGORIES_SUCCESS = 'content_categories_success';
export const CONTENT_CATEGORIES_FAILURE = 'content_categories_failure';

export const CONTENT_SUBCATEGORIES_REQUEST = 'CONTENT_SUBCATEGORIES_REQUEST';
export const CONTENT_SUBCATEGORIES_SUCCESS = 'CONTENT_SUBCATEGORIES_SUCCESS';
export const CONTENT_SUBCATEGORIES_FAILURE = 'CONTENT_SUBCATEGORIES_FAILURE';

export const CONTENT_CATEGORY_ITEMS_REQUEST = 'CONTENT_CATEGORY_ITEMS_REQUEST';
export const CONTENT_CATEGORY_ITEMS_SUCCESS = 'CONTENT_CATEGORY_ITEMS_SUCCESS';
export const CONTENT_CATEGORY_ITEMS_FAILURE = 'CONTENT_CATEGORY_ITEMS_FAILURE';
export const SET_CONTENT_SUBCATEGORIES = 'SET_CONTENT_SUBCATEGORIES';
export const CONTENT_CATEGORY_LOADING = 'CATEGORY_LOADING';
export const SET_CONTENT_SUBCATEGORY_ITEMS = 'SET_SUBCATEGORY_ITEMS';
